### PR TITLE
Merge _support folder into utils.

### PR DESCRIPTION
**Pull request by jcfranco**
**Related Issue:** N/A

## Summary

Merges folders since both include utilities.

## Notes

* Builds fine and tests are ✅.
* This does affect the generated output files.

### CODE REVIEW

**Comment by driskull** [comment]
Should this util move too? `https://github.com/Esri/calcite-app-components/blob/master/src/utils/localStorage.ts`

**Comment by jcfranco** [comment]
Maybe. I tackled the ones under components since those are definitely mergeable. @pr3tori4n WDYT?

**Comment by driskull** [comment]
I think we could move the other utility in this folder as well.

**Comment by jcfranco** [comment]
All component utils are now under the same folder. 🔧

**Pull request merged**
