### PR TITLE
Asangma/valuelist split

### PR DESCRIPTION
**Pull request by asangma**
**Related Issue:** #279

## Summary
Styles and some structural updates.

### CODE REVIEW

**Comment by asangma** [comment]
Changes to demo are to ensure styling works for more realistic content.

**Comment by asangma** [comment]
By design.

**Comment by pr3tori4n** [comment]
I would say it might be worth it to try darkening it or something, so you can see the outline of the button.

**Comment by asangma** [comment]
> I would say it might be worth it to try darkening it or something

I could see that. Let's consider it a future enhancement. I'm matching the styles that I ran by Mitch. I think if we see issues with this, we can update the :hover stat at the calcite-action level.

**Comment by asangma** [comment]
MURGLING!

**Pull request merged**
