### PR TITLE
fix(block): Avoid extra padding applied to slotted icon content

### PR DESCRIPTION
**Pull request by jcfranco**
**Related Issue:** #791 

## Summary

This removes unwanted padding on the icon slot. This was a regression from #763 (oversight on my part 😅).

### CODE REVIEW

**Comment by asangma** [comment]
👀

**Comment by asangma** [comment]
@jcfranco I guess I'm not clear on the need for the `::slotted(*)` selector. 🤔

**Comment by jcfranco** [comment]
> I guess I'm not clear on the need for the ::slotted(*) selector. 🤔

That's the only way I could get the consistent padding for content (default slot) across browsers. Nesting `::slotted` anywhere else would cause Edge to ignore it. Let me know if you have a cleaner way.

**Comment by asangma** [comment]
Could apply the padding to `.content`?

**Comment by jcfranco** [comment]
That has a side effect when you have a block w/ no content (`.container` should have no padding when empty). E.g., block w/ heading + icon/control.

**Comment by asangma** [comment]
I see. `:empty`?

**Comment by jcfranco** [comment]
I'll try that out. I can't recall if I had issues with it. Stay tuned...

**Comment by jcfranco** [comment]
WRT `:empty`, this won't work since it's never empty due to the slot. 

After thinking a little bit more on the extra padding, I think you’re right and we can always apply it to the content node. My changes were trying to address a problem only visible when you set the ___block to be open without any content___ (hence the visible empty content), which is an invalid use case.

**Comment by jcfranco** [comment]
@asangma Can you review again? I'll tidy up the story file, but the rest should stay the same.

**Pull request merged**
