### PR TITLE
simplify CSS for flow-item and panel

### PR DESCRIPTION
**Pull request by pr3tori4n**
**Related Issue:** #590

## Summary

I removed some of the % sizing and some display flex that seemed to not be necessary to achieve the desired layout for the flow-item + panel.
As best I can tell the layout for these two components is the same even with all of these style deletions.
@asangma @kat10140 please keep me honest here. If so, I think this would be a good simplification to go forward with.

### CODE REVIEW

**Comment by driskull** [comment]
I'll defer to @asangma for these changes. Might be good to test these against map viewer before merging.

**Comment by pr3tori4n** [comment]
@asangma can you please review this PR?

**Comment by driskull** [comment]
@pr3tori4n going to close this. Feel free to reopen and fix merge conflicts.

**Comment by jcfranco** [comment]
@pr3tori4n @asangma Safari testing looks good. 👍 

<details>
<summary>Chrome/Safari comparison</summary>

Screen Shot 2020-01-07 at 11 03 06 AM
Screen Shot 2020-01-07 at 11 03 43 AM
Screen Shot 2020-01-07 at 11 03 54 AM
Screen Shot 2020-01-07 at 11 04 04 AM
Screen Shot 2020-01-07 at 11 04 28 AM
Screen Shot 2020-01-07 at 11 04 40 AM
Screen Shot 2020-01-07 at 11 05 47 AM
Screen Shot 2020-01-07 at 11 05 54 AM

</details>

**Comment by driskull** [comment]
@pr3tori4n @asangma whats the status on this? Getting a little stale.

**Comment by pr3tori4n** [comment]
@driskull I'm not sure Alan has time to prioritize this right now so we can close it if you're good with that.

**Pull request closed without merging**
