### PR TITLE
feat(action): add scales to Action

### PR DESCRIPTION
**Pull request by asangma**
**Related Issue:** #759

## Summary
Add scales to Action.

`@Prop({ reflect: true }) scale: CalciteScale = "m";`

cc @AdelheidF

### CODE REVIEW

**Comment by asangma** [comment]
@jcfranco Shoowah.

**Comment by asangma** [comment]
@driskull Ah right. I could use some halp with that. 

@jcfranco thanks for reminding me to do the demos. It surfaced some fun stuff.

**Comment by driskull** [comment]
@asangma dont forget the storyboard knob too

**Comment by driskull** [comment]
@asangma can you just add the knob to the story and create an issue for me to deprecate the compact property?

**Comment by asangma** [comment]
@driskull Added the knob and created the [prop deprecation issue](#794).

**Comment by asangma** [comment]
@kat10140 Please check me on the Storybook and readme.

**Comment by kat10140** [comment]
Yay Alern!

**Comment by asangma** [comment]
Thanks!

**Pull request merged**
