### PR TITLE
Added foreground styles

### PR DESCRIPTION
**Pull request by asangma**
**Related Issue:** #139. 

## Summary
Added some styles for color

- Block
- Shell > footer

### CODE REVIEW

**Comment by driskull** [comment]
@asangma can you just search for where those two variables are used and make sure they are in the right places?

**Comment by asangma** [comment]
Thanks @driskull. I def was thinking along the same lines. Didn't know if we wanted to make all those changes tied to this issue, but I'm happy to do it.

**Comment by driskull** [comment]
@asangma I'm ok with merging this and then having a separate issue to refactor some of it. 👍

**Comment by asangma** [comment]
Coo. 
Refactor issue created: #175.

**Comment by asangma** [comment]
Thanks y'all.!

**Pull request merged**
