### PR TITLE
Enhancement: Add events to notify app when panel size has changed #223

### PR DESCRIPTION
**Pull request by driskull**
**Related Issue:** #223

## Summary

Enhancement: Add events to notify app when panel size has changed #223

### CODE REVIEW

**Comment by driskull** [comment]
> Would something similar work here?

@jcfranco what are you suggesting? having the event names change? 

These are tied to a property though. Since we can't watch a property, this is how a user would know they changed. right?

**Comment by jcfranco** [comment]
> what are you suggesting? having the event names change?

Yes. I'm suggesting a name change to `calcite<Bla>Toggle` for an event that fires based on expanding/collapsing. With regards to knowing the actual value, can't users get that from the `target`?

**Comment by driskull** [comment]
> Yes. I'm suggesting a name change to calcite<Bla>Toggle for an event that fires based on expanding/collapsing

Ok, ill change to `Toggle` instead of `Change`.

> With regards to knowing the actual value, can't users get that from the target?

Yep, ill remove passing that info

**Comment by driskull** [comment]
@jcfranco updated!

**Comment by jcfranco** [comment]
My bad, I should've been clearer in my comment. I meant to suggest: `calciteActionBarToggle` and `calciteShellPanelToggle`.

**Comment by driskull** [comment]
> My bad, I should've been clearer in my comment. I meant to suggest: calciteActionBarToggle and calciteShellPanelToggle.

Hmm. that seems kind of vague though. What if there's another toggle that happens with a different button? Its related to the attribute change

**Comment by driskull** [comment]
@jcfranco updated

**Comment by jcfranco** [comment]
> Hmm. that seems kind of vague though. 

That's why I wanted to know what your thoughts were. 😄

> What if there's another toggle that happens with a different button? Its related to the attribute change

My suggested event name reflects the change between expanded/collapsed and doesn't really care about how it happened. This doesn't work as nicely if there's a strong need to differentiate.

**Pull request merged**
